Repository juninhokaponne/chat-real, pull requests merged in 2025-10, with the labels that each got.

#23 Fix duplicate video
  package-lock.json
  src/components/VideoContainer/index.tsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, Core

#25 implemented Access camera denial recovery
  package-lock.json
  package.json
  src/components/VideoChat/index.tsx
  src/hooks/useVideoChat.ts
  src/types/index.ts
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#28 prevent memory leaks by pausing video elements during cleanup
  src/hooks/useVideoChat.ts
Labels: hacktoberfest, hacktoberfest-accepted, Core

#34 fix: resolved the issue video display on screen (fixed #22)
  src/components/CameraTest/index.tsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#37 Add audio visualizer to camera test
  src/components/CameraTest/CameraTest.module.css
  src/components/CameraTest/index.tsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#53 Camera access and enhanced UI in cameratest
  src/components/CameraTest/CameraTest.module.css
  src/components/CameraTest/index.tsx
Labels: bug, hacktoberfest, hacktoberfest-accepted, Core
